packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/engines"
  - "@heroui/shared-utils"
  - "@sentry/cli"
  - esbuild
  - prisma
  - protobufjs
  - puppeteer
  - sharp
  - core-js
  - sharp
  - unrs-resolver
  - ws
