export enum QueueStatus {
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  BOOKED = "BOOKED",
  CALLED = "CALLED",
  IN_CONSULTATION = "IN_CONSULTATION",
  SKIPPED = "SKIPPED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
}
